spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: wqkant
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    root: info
    com.wq: debug
  file: log/blog-dev.log

server:
  port: 8081